---
version: '3.7'
services:

    nginx:
      image: nginx
      depends_on: 
      - client
      - server
      volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
      ports:
      - target: 80
        protocol: tcp
        published: 80
      container_name: nginx


    server:
      build: 
        context: ./server
      expose: 
      - '8080'
      container_name: server
      depends_on:
      - mongo

    client:
      build: 
        context: ./client
      expose: 
      - '3000'   
      environment:
      - REACT_APP_SERVICE_HOST=${REACT_APP_SERVICE_HOST}
      container_name: client
      
    mongo:
      image: mongo
      expose: 
      - '27017'      
      container_name: mongo

    mongo-seed:
      image: fvilers/mongo-seed:1.0.0
      environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      volumes:
      - ./data:/data
      command:
      - "mongoimport --host mongo --port 27017 --db test --mode upsert --type json --file /data/account.json --jsonArray"

  
...

